@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "AddressBook Storage" #F4F6F6{
Class "<<interface>>\nAddressBookStorage" as AddressBookStorage
Class JsonAddressBookStorage
Class JsonSerializableAddressBook
Class JsonAdaptedPerson
Class JsonAdaptedTag
}

package "Command History Storage" #F4F6F6{
Interface "<<interface>>\nCommandHistoryStorage" as CommandHistoryStorage
Interface "<<interface>>\nReadOnlyCommandHistory" as ReadOnlyCommandHistory
Class "JsonStorage" as JsonStorage
Class "JsonSerializable" as JsonSerializable
Class JsonCommandHistoryStorage
Class JsonSerializableCommandHistory
}

}

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" AddressBookStorage
StorageManager -up-> "1" CommandHistoryStorage

Storage -left-|> UserPrefsStorage
Storage --|> AddressBookStorage
Storage --|> CommandHistoryStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonAddressBookStorage .up.|> AddressBookStorage
JsonAddressBookStorage ..> JsonSerializableAddressBook
JsonSerializableAddressBook --> "*" JsonAdaptedPerson
JsonAdaptedPerson --> "*" JsonAdaptedTag

JsonCommandHistoryStorage -up-|> JsonStorage
JsonCommandHistoryStorage .up.|> CommandHistoryStorage
JsonCommandHistoryStorage ..> JsonSerializableCommandHistory
JsonCommandHistoryStorage ..> ReadOnlyCommandHistory
JsonSerializableCommandHistory ..> ReadOnlyCommandHistory
@enduml