name: Java Code Quality Check (PMD)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pmd:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Run PMD
      uses: pmd/pmd-github-action@v1
      with:
        rulesets: category/java/design.xml, category/java/bestpractices.xml # Or your custom ruleset
        failOnViolation: true # Fail the build if PMD finds violations
